### ISSUE TITLE
Asking your work on ChestX-ray8 paper reproduce

### ISSUE THREAD

**Issue by yudabi** [TRKuan/cxr8#5]
Hi TRKuan,

I am a master student at University of Georgia and now I have a task to improve the result of this paper. I saw you have done a great job by using pytorch to reproduce this paper's result. Now in my lab, we have a new method that can improve this result significantly, but it still need time to work on coding. Could you provide your email or other contact method that we can get in touch to discuss this paper? Or if you are a Chinese, you can give me your WeChat. If possible, we can work together and get this paper's result improved, then we can publish a new paper on top conference. 

Best wishes,

Yuda Bi

**Comment by TRKuan** [comment]
Hi, I updated the email in my profile. You can email me for further discussion.
